= Policies Engine
:source-language: java


[.lead]
This project contains the execution engine for policies service. For the user-facing UI-backend see https://github.com/RedHatInsights/policies-ui-backend

== Run

Running Kafka instance is required to process inbound messages through the queue. If none exists, one can start Kafka with ``docker run --rm -e RUNTESTS=0 --net=host lensesio/fast-data-dev``

To start a clean instance of Policies Engine, run in this directory: ``./mvnw quarkus:dev``

REST-interface will be available by default from port ``8084`` (and ``8080`` in containers).

== License

Policies Engine is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015-2020 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
