= Policies Engine
:source-language: java

[.lead]
This project contains the execution engine for policies service. For the user-facing UI-backend see https://github.com/RedHatInsights/policies-ui-backend

This repository contains parts of the Hawkular-Alerts core. It is not interchangeable with the previous maven modules as stuff has been moved around, removed and modified. For the old documentation (not necessarily relevant in all parts), see:

link:http://www.hawkular.org/community/docs/developer-guide/alerts-v2.html[Hawkular Alerting User Guide].

link:http://www.hawkular.org/docs/rest/rest-alerts-v2.html[Hawkular Alerting REST API]

=== Module dependencies

``external`` module depends on ``engine``

``engine`` module depends on ``api``

``engine`` is using a modified version of Infinispan's RocksDB cache-store. To build it, use the link:https://github.com/burmanm/infinispan/tree/10.1-mod[10.1-mod] branch. In the ``persistence/rocksdb`` run ``./mvnw clean install deploy -DskipTests`` and copy the resulting files from ``target/mvn-repo`` to ``engine/src/main/resources/repo``. Modify the ``.pom`` file by making the parent point to ``10.1.8.Final`` and then update the SNAPSHOT version in `dependencyManagement` to enable the newer build. You can also update the ``.md5`` and `.sha1` files with `openssl dgst -sha1 file.pom` after modifying the parent version.

== Run

See link:https://github.com/RedHatInsights/policies-engine/tree/master/external[external] module for instructions. Requires Kafka and Java 11 (or newer).

== License

Policies Engine is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015-2020 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
