= Custom Policies Engine

This project contains the execution engine for custom policies.
For the user-facing UI-backend see https://github.com/RedHatInsights/custom-policies-ui-backend

For the engine to run it needs access to postgres and Kafka

== Get started

To set up Postgres and Kafka, you can use the Docker-compose mechanism that is
described in the https://github.com/RedHatInsights/custom-policies-ui-backend/README.adoc[README of the UI-Backend].

=== Engine

[source,shell]
----
mvn compile quarkus:dev
----
Service then listens on localhost:8083, Debugger on port 5006


== Add new policy from UI (frontend)

There are 3 sample files
* bad-policy.json: Invalid rule syntax
* bad-policy2.json : Duplicate policy name
* policy.json : A good new policy

Add via

[source,shell]
----
 curl -X POST -i -H 'content-type: application/json' -H 'accept: application/json' http://localhost:8080/api/v1/policies/1 -d @<filename>
----


== Evaluate facts against rules on the engine
This is internally used from the UI-backend to verify rules

[source,shell]
----
curl -X POST -i -H 'content-type: application/json' -H 'accept: application/json' http://localhost:8083/api/v1/eval/1 -d @facts.json
----


== Event handling in the Engine

The engine has a DummyEventProducer, which creates a HostEvent every 30s and sends it to Kafka's 'event' topic.
The Event is received by the PolicyRetriever, which then extracts the customer id, loads all the
stored policies for that customer, evaluates them and sends a result on the 'notification' topic.


== OpenAPI Endpoint / Swagger-UI

OpenAPI spec of the API is available under http://localhost:8083/openapi

When the server is running in dev mode, there is also the Swagger-UI available under
http://localhost:8083/swagger-ui/

== Container usage

The `deploy/` directory contains a script to create a container image of the engine.

[source,shell]
----
cd deploy
sh create_docker_image.sh
----

To run the image you need to pass some parameters:

[source,shell]
----
docker run -it -p 8083:8083 \                       # <1>
    -e kafka.bootstrap.servers=1.2.3.4:9092 \       # <2>
    -e quarkus.datasource.url=jdbc://1.2.3.4:5432/postgres \ # <3>
     cp-engine
----
<1> Expose the internal port.
<2> Url of your Kafka broker -- see also below
<3> Database URL of your postgres instance

You can also pass the Postgres user name + password - see Dockerfile.

=== A note on the Kafka broker configuration

For the above to work you need to make sure that Kafka is not (only) advertising
a listener to localhost. In this case, Quarkus could connect to Kafka and Kafka will
reply with "Hey I a listening on localhost:9092", and Quarkus would then try to
connect on localhost:9092, which is expected to be inside the container.

In your Kafka configuration you should thus put something like

[source,shell]
----
KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://1.2.3.4:9092
----

to match the `kafka.bootstrap.servers` from above.


