---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: policies-engine
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: policies-engine
    labels:
      app: policies-engine
  spec:
    envName: ${ENV_NAME}
    dependencies:
    - host-inventory
    - ingress
    - policies-ui-backend
    database:
      sharedDbAppName: policies-ui-backend
    kafkaTopics:
    - topicName: platform.inventory.events
      partitions: 64
      replicas: 3
    - topicName: platform.notifications.ingress
      partitions: 3
      replicas: 3
    testing:
      iqePlugin: policies
    deployments:
    - name: service
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        volumes:
        - name: certs
          emptyDir: {}
        volumeMounts:
        - name: certs
          mountPath: /tmp
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: ENV_NAME
          value: ${ENV_NAME}
        - name: ENV_BASE_URL
          value: ${ENV_BASE_URL}
        - name: EXTERNAL_LOGGING_LEVEL
          value: ${EXTERNAL_LOGGING_LEVEL}
        - name: GC_CONTAINER_OPTIONS
          value: "-XX:+UseG1GC"
        - name: QUARKUS_HTTP_PORT
          value: "8000"
        - name: QUARKUS_LOG_CLOUDWATCH_ENABLED
          value: ${CLOUDWATCH_ENABLED}
        - name: QUARKUS_LOG_CLOUDWATCH_LOG_STREAM_NAME
          value: ${HOSTNAME}
        - name: QUARKUS_LOG_SENTRY
          value: ${SENTRY_ENABLED}
        - name: QUARKUS_LOG_SENTRY_DSN
          value: "${SENTRY_DSN}"
        - name: QUARKUS_LOG_SENTRY_ENVIRONMENT
          value: ${ENV_NAME}
        - name: NOTIFICATIONS_SEND_AS_CLOUD_EVENT
          value: ${NOTIFICATIONS_SEND_AS_CLOUD_EVENT}
parameters:
- name: CLOUDWATCH_ENABLED
  description: Enable Cloudwatch (or not)
  value: "false"
- name: CPU_LIMIT
  description: CPU limit
  value: 250m
- name: CPU_REQUEST
  description: CPU request
  value: 125m
- name: ENV_NAME
  description: ClowdEnvironment name (ephemeral, stage, prod)
  required: true
- name: IMAGE
  description: Image URL
  value: quay.io/redhat-services-prod/insights-management-tenant/insights-policies/policies-engine
- name: IMAGE_TAG
  description: Image tag
  value: latest
- name: EXTERNAL_LOGGING_LEVEL
  value: INFO
- name: MEMORY_LIMIT
  description: Memory limit
  value: 1000Mi
- name: MEMORY_REQUEST
  description: Memory request
  value: 500Mi
- name: MIN_REPLICAS
  value: "1"
- name: SENTRY_ENABLED
  description: Enable Sentry (or not)
  value: "false"
- name: SENTRY_DSN
  description: Sentry DSN URL
  value: ""
- name: NOTIFICATIONS_SEND_AS_CLOUD_EVENT
  description: Send the notifications as cloud events
  value: "false"
- name: ENV_BASE_URL
  value: https://console.redhat.com
  description: The environment's base URL
