---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: policies-engine
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: policies-engine-data
    labels:
      app: policies-engine
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${INFINISPAN_STORAGE}
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: policies-engine
    labels:
      app: policies-engine
  spec:
    envName: ${ENV_NAME}
    dependencies:
    - host-inventory
    - ingress
    - policies-ui-backend
    database:
      sharedDbAppName: policies-ui-backend
    jobs:
    - name: org-id-populator
        podSpec:
          image: quay.io/cloudservices/tenant-utils:latest
          command:
            - ./org-id-column-populator
            - -C
            - -a
            - account_id
            - -o
            - org_id
            - -t
            - account_latest_update
            - --ean-translator-addr
            - http://${TENANT_TRANSLATOR_HOST}:${TENANT_TRANSLATOR_PORT}
          env:
            - name: TENANT_TRANSLATOR_HOST
              value: ${TENANT_TRANSLATOR_HOST}
            - name: TENANT_TRANSLATOR_PORT
              value: ${TENANT_TRANSLATOR_PORT}
            - name: LOG_FORMAT
              value: ${LOG_FORMAT}
            - name: LOG_BATCH_FREQUENCY
              value: '1'
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 512Mi
    kafkaTopics:
    - topicName: platform.inventory.events
      partitions: 64
      replicas: 3
    - topicName: platform.notifications.ingress
      partitions: 3
      replicas: 3
    testing:
      iqePlugin: policies
    deployments:
    - name: service
      replicas: ${{REPLICAS}}
      strategy:
        type: Recreate
      webServices:
        public:
          enabled: true
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        volumes:
        - name: policies-engine-data
          persistentVolumeClaim:
            claimName: policies-engine-data
        - name: certs
          emptyDir: {}
        volumeMounts:
        - name: policies-engine-data
          mountPath: /data
        - name: certs
          mountPath: /tmp
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: ENGINE_ALERTS_ENGINE_PERIOD
          value: ${ENGINE_ALERTS_ENGINE_PERIOD}
        - name: ENV_NAME
          value: ${ENV_NAME}
        - name: EXTERNAL_LOGGING_LEVEL
          value: ${EXTERNAL_LOGGING_LEVEL}
        - name: GC_CONTAINER_OPTIONS
          value: "-XX:+UseG1GC"
        - name: GC_MAX_METASPACE_SIZE
          value: "256"
        - name: JAVA_CORE_LIMIT
          value: "0"
        - name: _JAVA_OPTIONS
          value: -Dhawkular.data=/data -Dengine.alerts.condition-evaluation-time=false -Dengine.data-driven-triggers-enabled=false
        - name: LIGHTWEIGHT_ENGINE_DB_LOADING_ENABLED
          value: ${LIGHTWEIGHT_ENGINE_DB_LOADING_ENABLED}
        - name: LIGHTWEIGHT_ENGINE_KAFKA_PROCESSING_ENABLED
          value: ${LIGHTWEIGHT_ENGINE_KAFKA_PROCESSING_ENABLED}
        - name: QUARKUS_HTTP_PORT
          value: "8000"
        - name: QUARKUS_LOG_CLOUDWATCH_ENABLED
          value: ${CLOUDWATCH_ENABLED}
        - name: QUARKUS_LOG_CLOUDWATCH_LOG_STREAM_NAME
          value: ${HOSTNAME}
        - name: QUARKUS_LOG_SENTRY
          value: ${SENTRY_ENABLED}
        - name: QUARKUS_LOG_SENTRY_DSN
          value: https://a22a69dec467495e8dabc9a937104f34@o271843.ingest.sentry.io/5217678?environment=${ENV_NAME}
        - name: QUARKUS_LOG_SENTRY_ENVIRONMENT
          value: ${ENV_NAME}
parameters:
- name: CLOUDWATCH_ENABLED
  description: Enable Cloudwatch (or not)
  value: "false"
- name: CPU_LIMIT
  description: CPU limit
  value: 1000m
- name: CPU_REQUEST
  description: CPU request
  value: 500m
- name: ENGINE_ALERTS_ENGINE_PERIOD
  description: Delay in milliseconds between two executions of the TimerTask that processes the events
  value: "2000"
- name: ENV_NAME
  description: ClowdEnvironment name (ephemeral, stage, prod)
  required: true
- name: IMAGE
  description: Image URL
  value: quay.io/cloudservices/policies-engine
- name: IMAGE_TAG
  description: Image tag
  value: latest
- name: INFINISPAN_STORAGE
  displayName: Infinispan's persistent storage size
  description: Amount of storage to request for the database persistent volume
  value: 10Gi
- name: EXTERNAL_LOGGING_LEVEL
  value: INFO
- name: LIGHTWEIGHT_ENGINE_DB_LOADING_ENABLED
  value: "false"
- name: LIGHTWEIGHT_ENGINE_KAFKA_PROCESSING_ENABLED
  value: "false"
- name: MEMORY_LIMIT
  description: Memory limit
  value: 3Gi
- name: MEMORY_REQUEST
  description: Memory request
  value: 1.5Gi
- name: REPLICAS
  value: "1"
- name: SENTRY_ENABLED
  description: Enable Sentry (or not)
  value: "false"
- description: Host for the EAN to OrgId translator.
  name: TENANT_TRANSLATOR_HOST
  required: true
  value: 'apicast.3scale-dev.svc.cluster.local'
- description: Port for the EAN to OrgId translator.
  name: TENANT_TRANSLATOR_PORT
  required: true
  value: '8892'
